<div class="jumbotron">
    <h3>Хотите с нами связаться ?</h3> 
    <h3>Отправте нам сообщение!</h3>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="feedback">
            <form method="POST" action="" >
                <div class="control-group">
                    <label class="control-label" for="massege">Cообщение</label> 
                    <div class="controls"><textarea id="massege" name="massege" rows=6 placeholder="Введите Ваше сообщение" required></textarea> </div><br/>
                </div>
                <div class="control-group">
                    <label class="control-label" for="name">Имя</label> 
                    <div class="controls"><input id="name" type="text" name="name" placeholder="Введите ваше имя" required/> </div><br/>
                </div>
                <div class="control-group">
                    <label class="control-label" for="email">Email</label> 
                    <div class="controls"><input id="email" tymassegepe="email" name="email" placeholder="Введите ваш email" required/> </div><br/>
                </div>
                <div class="control-group">
                    <div class="controls"><input type="submit" class="btn btn-primary"/> </div>
                </div>
            </form>
        </div>
    </div>
</div>