<div class="jumbotron">
    <h2>Наши контакты</h2>
</div>
<div class="row">
    <div class="col-md-12">
        <div>
            <p><img src="img/phone.png" alt="logo_phone"/> +38 056 376 9066</p>
            <p><img src="img/phone.png" alt="logo_phone"/> +38 099 731 8385</p>
            <p><img src="img/phone.png" alt="logo_phone"/> +38 096 084 2513</p>
        </div>
        <div>
            <p><img src="img/location.png" alt="logo_location"/>Украина, Днепропетровск, ул. Троицкая (бывш. Красная), 21</p>
        </div>
        <div><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5291.418369820885!2d35.03822576929!3d48.4621091405487!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40dbe2e09d99958b%3A0x7bbfa45acac728b4!2z0LLRg9C7LiDQotGA0L7Rl9GG0YzQutCwLCAyMSwg0JTQvdGW0L_RgNC-0L_QtdGC0YDQvtCy0YHRjNC6LCDQlNC90ZbQv9GA0L7Qv9C10YLRgNC-0LLRgdGM0LrQsCDQvtCx0LvQsNGB0YLRjCwgNDkwMDA!5e0!3m2!1sru!2sua!4v1459554883725" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe></div>
    </div>
</div>