<div class="jumbotron">
    <h1>Голубой слоник</h1>
    <p>Нужен сайт? Хотите сами научиться создавать сайты, освоить профессию PHP developer? Тогда мы Вам поможем!</p>
    <p>Студия "Голубой слоник" была создана в 2015 году, но уже успела стать лидером рынка!<span id="about"> В чем же секрет?</span></p>
</div>
<div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Команда проФФесионалов</h3>
                </div>
                <div class="panel-body">
                    <div class="team_photo"><img src="img/1.jpg" alt="professionals1"/></div>
                    <div class="team_photo"><img src="img/2.jpg" alt="professionals2"/></div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">

        </div>
        <div class="col-md-8">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Опытный преподаватель</h3>
                </div>
                <div class="panel-body">
                    <div class="prepod_photo"><img src="img/3.jpg" alt="prepod"/></div>
                </div>
            </div>
        </div>
        <div class="col-md-2">

        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Современное оборудывание</h3>
                </div>
                <div class="panel-body">
                    <div class="team_photo"><img src="img/4.jpg" alt="computer1"/></div>
                    <div class="team_photo"><img src="img/5.jpg" alt="computer2"/></div>
                </div>
            </div>
        </div>
    </div>
</div>
